; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][version] = "3.0-rc3"

projects[admin_language][version] = "1.x-dev"

projects[advanced_help][version] = "1.0"

projects[ctools][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[contact_feature][download][type] = ""
projects[contact_feature][download][url] = ""
projects[contact_feature][type] = "module"
projects[contact_feature][subdir] = "custom_features"
projects[contact_feature][version] = "1.0"

projects[content_type_groups][version] = "1.3"

projects[date][version] = "2.5"

projects[devel][version] = "1.3"

projects[ds][version] = "1.5"

projects[entity][version] = "1.0-rc3"

projects[entity_translation][version] = "1.0-alpha2"

projects[entityreference][version] = "1.0-rc3"

projects[entityreference_view_widget][version] = "1.0-alpha2+0-dev"

projects[features][version] = "1.0-rc3"

projects[field_permissions][version] = "1.0-beta2"

projects[google_analytics][version] = "1.2"

projects[imce][version] = "1.5"

projects[l10n_update][version] = "1.0-beta3"

projects[markdown][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[markdown_feature][download][type] = ""
projects[markdown_feature][download][url] = ""
projects[markdown_feature][type] = "module"
projects[markdown_feature][subdir] = "custom_features"
projects[markdown_feature][version] = "1.0"

projects[module_filter][version] = "1.6"

projects[node_export][version] = "3.0-rc3+38-dev"

projects[oauth][version] = "3.0"

projects[page_title][version] = "2.7"

projects[panels][version] = "3.2"

projects[pathauto][version] = "1.1"

projects[privatemsg][version] = "1.3"

projects[quicktabs][version] = "3.4"

projects[redirect][version] = "1.0-beta4"

projects[reg_with_pic][version] = "1.0"

projects[services][version] = "3.1"

projects[rules][version] = "2.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_aggregates_feature][download][type] = ""
projects[scoga_aggregates_feature][download][url] = ""
projects[scoga_aggregates_feature][type] = "module"
projects[scoga_aggregates_feature][subdir] = "custom_features"
projects[scoga_aggregates_feature][version] = "1.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_core_feature][download][type] = ""
projects[scoga_core_feature][download][url] = ""
projects[scoga_core_feature][type] = "module"
projects[scoga_core_feature][subdir] = "custom_features"
projects[scoga_core_feature][version] = "1.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_pages_feature][download][type] = ""
projects[scoga_pages_feature][download][url] = ""
projects[scoga_pages_feature][type] = "module"
projects[scoga_pages_feature][subdir] = "custom_features"
projects[scoga_pages_feature][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_rfid_feature][download][type] = ""
projects[scoga_rfid_feature][download][url] = ""
projects[scoga_rfid_feature][type] = "module"
projects[scoga_rfid_feature][subdir] = "custom_features"
projects[scoga_rfid_feature][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_wishlist_feature][download][type] = ""
projects[scoga_wishlist_feature][download][url] = ""
projects[scoga_wishlist_feature][type] = "module"
projects[scoga_wishlist_feature][subdir] = "custom_features"
projects[scoga_wishlist_feature][version] = "1.0"

projects[security_review][version] = "1.0"

projects[subform][version] = "1.0-alpha1"

projects[title][version] = "1.0-alpha3"

projects[token][version] = "1.1"

projects[user_relationships][version] = "1.0-alpha4"

projects[userpoints][version] = "1.0"

projects[userpoints_nc][version] = "1.0"

projects[uuid][version] = "1.0-alpha3"

projects[uuid_features][version] = "1.0-alpha1"

projects[variable][version] = "2.1"

projects[views][version] = "3.3"

projects[wysiwyg][version] = "2.1"

; Themes
projects[corporateclean][version] = "1.5"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_aggregated][download][type] = ""
projects[scoga_aggregated][download][url] = ""
projects[scoga_aggregated][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_core][download][type] = ""
projects[scoga_core][download][url] = ""
projects[scoga_core][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_rfid][download][type] = ""
projects[scoga_rfid][download][url] = ""
projects[scoga_rfid][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[scoga_wishlist][download][type] = ""
projects[scoga_wishlist][download][url] = ""
projects[scoga_wishlist][type] = "module"

