<?php
module_load_include( 'inc', 'scoga', 'scoga.constants' );
module_load_include( 'inc', 'scoga' );

define( 'SCOGA_PERM_ADMINISTER_SETTINGS', 'scoga administer settings' );

/**
 * implement hook_menu()
 */
function scoga_menu(){
    $items = array();
    $items[ 'admin/config/scoga' ] = array(
        'title' => t('SCOGA settings'),
        'description' => t('General settings for SCOGA'),
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array( SCOGA_PERM_ADMINISTER_SETTINGS ),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items[ 'admin/config/scoga/points' ] = array(
        'title' => t( 'SCOGA points settings' ),
        'description' => t( 'Points settings for SCOGA' ),
        'page callback' => 'drupal_get_form',
        'page arguments' => array( 'scoga_points_form' ),
        'access arguments' => array( SCOGA_PERM_ADMINISTER_SETTINGS ),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function scoga_points_form( $form, &$form_state ){

    $terms = _retrieve_terms_by_machinename( SCOGA_POINTS_VOCAB );
    foreach( $terms as $index => $term ){
        //cool down
        $form_elem_name = 'scoga_settings_' . strtolower( $term->name )  . '_cooldown';
        $form[ $form_elem_name ] = array(
            '#type' => 'textfield',
            '#title' => t('Cooldown for "' ) . $term->name .'"',
            '#description' => t('Define cooldown period for "' ) . $term->name . '" ' . t( 'in seconds, 0 for unlimited.'),
            '#default_value' => variable_get( $form_elem_name, 0 ),
            '#size' => 10,
            '#required' => TRUE
        );
    }
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save settings'),
    );

    return $form;
}

function scoga_points_form_submit( $form, &$form_state ){
    $terms = _retrieve_terms_by_machinename( SCOGA_POINTS_VOCAB );
    foreach( $terms as $index => $term ){
        //cooldown
        $form_elem_name = 'scoga_settings_' . strtolower( $term->name ) . '_cooldown';
        variable_set( $form_elem_name, $form_state['values'][$form_elem_name] );
    }
    drupal_set_message( t('The SCOGA points settings have been saved.') );
}
