<?php
/**
 * Created by JetBrains PhpStorm.
 * User: creynder
 * Date: 23/01/12
 * Time: 15:23
 * To change this template use File | Settings | File Templates.
 */


define( 'SCOGA_TIME_FORMAT', 'H:i:s d/m/Y' );
define( 'SCOGA_DEFAULT_LANG', LANGUAGE_NONE );
define( 'SCOGA_TEAM_NODETYPE', 'nodetype_team' );
define( 'SCOGA_CHECKIN_NODETYPE', 'nodetype_checkin' );
define( 'SCOGA_READER_NODETYPE', 'nodetype_rfidreader' );
define( 'SCOGA_POINTS_VOCAB', 'userpoints' );

define( 'SCOGA_DEFAULT_TEAM', 196 );
