<?php

define( 'SCOGA_PERM_ADMINISTER_SETTINGS', 'scoga administer settings' );

/**
 * implement hook_menu()
 */
function scoga_menu(){
    $items = array();
    $items[ 'admin/config/scoga' ] = array(
        'title' => t('SCOGA settings'),
        'description' => t('General settings for SCOGA'),
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array( SCOGA_PERM_ADMINISTER_SETTINGS ),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items[ 'admin/config/scoga/scoring' ] = array(
        'title' => t( 'SCOGA scoring settings' ),
        'description' => t( 'Scoring settings for SCOGA' ),
        'page callback' => 'drupal_get_form',
        'page arguments' => array( 'scoga_scoring_form' ),
        'access arguments' => array( SCOGA_PERM_ADMINISTER_SETTINGS ),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function scoga_scoring_form( $form, &$form_state ){

    $group = new ContentTypeGroup( SCOGA_PLAYERACTION_CONTENTTYPEGROUP );
    foreach( $group->typeList() as $type => $label ){
        $form_elem_name = 'scoga_settings_' . $type . '_score';
        $form[ $form_elem_name ] = array(
            '#type' => 'textfield',
            '#title' => t('Scoring for "' ) . $type .'"',
            '#description' => t('Defines the base score value of player action "' ) . $type . '"',
            '#default_value' => variable_get( $form_elem_name, 1 ),
            '#size' => 10,
            '#required' => TRUE
        );
    }
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save settings'),
    );

    return $form;
}

function scoga_scoring_form_submit( $form, &$form_state ){
    $group = new ContentTypeGroup( SCOGA_PLAYERACTION_CONTENTTYPEGROUP );
    foreach( $group->typeList() as $type => $label ){
        $form_elem_name = 'scoga_settings_' . $type . '_score';
        variable_set( $form_elem_name, $form_state['values'][$form_elem_name] );
    }
    drupal_set_message( t('The scoring settings have been saved.') );
}

/**
 * implements hook_node_presave
 * @param $node
 */

function scoga_node_presave( $node ){

    //if node of type checkin and published
    if( $node->type === SCOGA_CHECKIN_NODETYPE && $node->status == '1' ){
        $user_account = user_load( $node->uid );
        //var_dump( $user_account );
        $team_nid = $user_account->field_team_reference[ LANGUAGE_NONE ][ 0 ][ 'nid' ];
        $team_node = node_load( $team_nid );
        $score = $team_node->field_team_score_multiplier[ LANGUAGE_NONE ][ 0 ][ 'value' ] * variable_get( 'scoga_settings_' . SCOGA_CHECKIN_NODETYPE . '_score' );
        $node->field_checkin_score[ LANGUAGE_NONE ][ 0 ][ 'value' ] = $score;
        $team_node->field_team_score[ LANGUAGE_NONE ][ 0 ][ 'value' ] += $score;

        //update team node
        node_save( $team_node );
    }
}
