<?php
/**
 * Created by JetBrains PhpStorm.
 * User: creynder
 * Date: 23/01/12
 * Time: 15:23
 * To change this template use File | Settings | File Templates.
 */


define( 'SCOGA_TIME_FORMAT', 'H:i:s d/m/Y' );
define( 'SCOGA_DEFAULT_LANG', LANGUAGE_NONE );
define( 'SCOGA_TEAM_NODETYPE', 'kliek_team' );
define( 'SCOGA_SWIPE_NODETYPE', 'rfid_swipe' );
define( 'SCOGA_READER_NODETYPE', 'rfid_reader' );

define( 'SCOGA_PLAYERACTIONTYPE_VID', 3 );
define( 'SCOGA_DEFAULT_TEAM', 196 );
define( 'SCOGA_CHECKIN_TID', 1 );
