<?php
    /**
     * Created by JetBrains PhpStorm.
     * User: creynder
     * Date: 27/04/12
     * Time: 14:20
     * To change this template use File | Settings | File Templates.
     */
    define( 'SCOGA_WISHEDITEM_NODETYPE', 'nodetype_wished_item' );
    define( 'SCOGA_SETTING_MAX_WISHITEM_CREDIT', 'scoga_setting_max_wishitem_credit' );
    define( 'SCOGA_CREDITS_TID', '3' );

    module_load_include( 'api.inc', 'scoga_wishlist' );


    /**
     * implement hook_menu()
     */
    function scoga_wishlist_menu(){
        $items = array();
        $items[ SCOGA_ADMIN_PAGE . '/wishlist' ]=array(
            'title'             => t( 'SCOGA wishlist settings' ),
            'description'      => t( 'Wishlist settings for SCOGA' ),
            'type'              => MENU_NORMAL_ITEM,
            'file'             => 'scoga_wishlist.admin.inc',
            'page callback'    => 'drupal_get_form',
            'page arguments'   => array( 'scoga_wishlist_settings_form' ),
            'access arguments' => array( SCOGA_PERM_ADMINISTER_SETTINGS ),
        );


        return $items;
    }


    /**
     * TODO: extract contents to API method
     * implements hook_form_FORM_ID_alter
     * @param $form
     * @param $form_state
     * @param $form_id
     */
    function scoga_wishlist_form_nodetype_wished_item_node_form_alter( &$form, $form_state, $form_id ){
        global $user;

        $user_remaining_credits = userpoints_get_current_points( $user->uid, SCOGA_CREDITS_TID );

        if( $user_remaining_credits > 0 ){
            $credits_select_data = array(
                '_none' => '- Select a value -'
            );
            for( $i=0; $i < $user_remaining_credits; $i++ ){
                $value = $i+1;
                $credits_select_data[ $value ] = $value;
            }
        }else{
            $credits_select_data = array(
                '_none' => '- NOT ENOUGH CREDITS -'
            );
        }

        $field_name = 'field_wisheditem_award';
        $award_element = $form[ $field_name ];
        $lang = $award_element[ '#language' ];
        $award_element[ $lang ][ '#options' ] = $credits_select_data;
        $form[ $field_name ] = $award_element;

        $field_name = 'field_wisheditem_campaign';
        $campaign_element = $form[ $field_name ];
        $lang = $campaign_element[ '#language' ];
        $campaign_element[ $lang ][ '#default_value' ] = scoga_get_current_campaign_nid();
        $form[ $field_name ] = $campaign_element;

    }
    /**
     * TODO: extract contents to API method
     * implements hook_form_FORM_ID_alter
     *
     * @param $form
     * @param $form_state
     * @param $form_id
     */
    function scoga_wishlist_form_nodetype_wish_fulfilled_node_form_alter( &$form, $form_state, $form_id ){
        global $user;

        $user_profile = user_load( $user->uid );
        module_load_include( 'api.wisheditem.inc', 'scoga_wishlist' );
        module_load_include( 'api.player.inc', 'scoga_core' );

        /*
         * wished item
         *
         */
        $wisheditem_nids = scoga_get_wisheditem_nids_for_uid( $user_profile->uid );

        $wishlist_select_data = array(
            '_none' => '- Select a value -'
        );
        foreach( $wisheditem_nids as $nid ){
            $wisheditem_node = node_load( $nid );
            $wishlist_select_data[ $nid ] = $wisheditem_node->title;
        }

        //TODO: OPTIMIZE THIS, it simply overwrites a list of ALL wished items
        $wisheditem_element = $form[ 'field_wishfulfilled_wisheditem' ];
        $lang = $wisheditem_element[ '#language' ];
        $wisheditem_element[ $lang ][ '#options' ] = $wishlist_select_data;
        $form[ 'field_wishfulfilled_wisheditem' ] = $wisheditem_element;


        /*
         * fulfiller
         */
        $user_team_values = field_get_items( 'user', $user_profile, 'field_user_team' );
        $team_nid = ( $user_team_values ) ? $user_team_values[ 0 ][ 'target_id' ] : 0;

        $player_uids = scoga_get_player_uids_by_team_nid( $team_nid, TRUE ); //TRUE->negates

        $player_select_data = array(
            '_none' => '- Select a value -'
        );
        foreach( $player_uids as $uid ){
            $player_profile = user_load( $uid );
            $player_select_data[ $uid ] = $player_profile->name;
        }

        //TODO: OPTIMIZE THIS, it simply overwrites a list of ALL users

        $fulfiller_element = $form[ 'field_wishfulfilled_fulfiller' ];
        $lang = $fulfiller_element[ '#language' ];
        $fulfiller_element[ $lang ][ '#options' ] = $player_select_data;
        $form[ 'field_wishfulfilled_fulfiller' ] = $fulfiller_element;

        /*
         * title
         */
        $form[ 'title' ][ '#required' ] = FALSE;
        //hide the title field
        $form[ 'title' ][ '#access' ] = FALSE;

        //dsm( $form[ 'title' ] );
        $form[ 'title' ][ '#value' ] = 'wish fullfilled ' . $user->uid . ' ' . time();
    }
