<?php
/**
 * Created by JetBrains PhpStorm.
 * User: creynder
 * Date: 13/12/11
 * Time: 12:36
 * To change this template use File | Settings | File Templates.
 */
/**
 * Implements hook_perm().
 */

function scoga_resource_checkin_permission() {
  return array(
    'Access SCOGA Checkin service' => array(
      'title' => t('Access SCOGA Checkin service'),
      'description' => t('Make calls to the SCOGA checkin service'),
    ),
  );
}
/**
* Implements hook_services_resources().
*/
function scoga_resource_checkin_services_resources(){
    return array(
        'reader_checkin' => array(
            'index' => array(
                'help' => 'List of "Checkin"',
                'file' => array(
                    'file' => 'inc',
                    'module' => 'scoga_resource_checkin'
                ),
                'callback' => '_reader_checkin_index',
                'access arguments' => array( 'Access SCOGA Checkin service' ),
                'args' => array(
                    array(
                        'name' => 'cardID',
                        'type' => 'string',
                        'description' => 'The unique ID of the card',
                        'source' => 'param',
                        'optional' => TRUE,
                    ),
                ),
            ),
            'create' => array(
                'help' => 'Creates a node of content type "Checkin"',
                'file' => array(
                    'file' => 'inc',
                    'module' => 'scoga_resource_checkin'
                ),
                'callback' => '_reader_checkin_create',
                'access arguments' => array( 'Access SCOGA Checkin service' ),
                'args' => array(
                    array(
                        'name' => 'cardID',
                        'type' => 'string',
                        'description' => 'The unique ID of the card',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'readerID',
                        'type' => 'string',
                        'description' => 'The unique ID of the RFID reader',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'timestamp',
                        'type' => 'int',
                        'description' => 'The unix epoch timestamp of checkin',
                        'source' => 'data',
                        'optional' => TRUE,
                        'default value' => -1
                    ),
                )
            )
        ),
    );
}
