<?php
/**
 * Created by JetBrains PhpStorm.
 * User: creynder
 * Date: 12/04/12
 * Time: 10:19
 * To change this template use File | Settings | File Templates.
 */

define( 'SCOGA_TIME_FORMAT', 'H:i:s d/m/Y' );

define( 'SCOGA_CAMPAIGNTEAM_NODETYPE', 'nodetype_campaign_team' );
define( 'SCOGA_TEAM_NODETYPE', 'nodetype_team' );
define( 'SCOGA_CHECKIN_NODETYPE', 'nodetype_checkin' );
define( 'SCOGA_READER_NODETYPE', 'nodetype_rfidreader' );
define( 'SCOGA_POINTS_VOCAB', 'userpoints' );

define( 'SCOGA_SCORE_TID', '4' );
