<?php
    /**
     * Created by JetBrains PhpStorm.
     * User: creynder
     * Date: 12/04/12
     * Time: 10:19
     * To change this template use File | Settings | File Templates.
     */


    define( 'SCOGA_PERM_ADMINISTER_SETTINGS', 'scoga administer settings' );

    define( 'SCOGA_TIME_FORMAT', 'H:i:s d/m/Y' );

    define( 'SCOGA_CAMPAIGN_NODETYPE', 'nodetype_campaign' );
    define( 'SCOGA_CAMPAIGNTEAM_NODETYPE', 'nodetype_campaign_team' );
    define( 'SCOGA_TEAM_NODETYPE', 'nodetype_team' );
    define( 'SCOGA_CHECKIN_NODETYPE', 'nodetype_checkin' );
    define( 'SCOGA_READER_NODETYPE', 'nodetype_rfid_reader' );
    define( 'SCOGA_POINTS_VOCAB', 'userpoints' );

    define( 'SCOGA_SETTINGS_CHECKIN_COOLDOWN', 'scoga_settings_checkin_cooldown' );
    define( 'SCOGA_SETTINGS_COMBOCHECKIN_TIMEFRAME', 'scoga_settings_combocheckin_timeframe' );
    define( 'SCOGA_SETTINGS_DEFAULT_USERNAME', 'scoga_settings_default_username' );
    define( 'SCOGA_SETTINGS_CURRENT_CAMPAIGN_NID', 'scoga_settings_current_campaign_nid' );

    define( 'SCOGA_SCORE_TID', '4' );
    define( 'SCOGA_DEFAULT_TEAM', 26 );
    define( 'SCOGA_CHECKINPARTNER_RTID', 1 );
