<?php
    /**
     * Created by JetBrains PhpStorm.
     * User: creynder
     * Date: 12/04/12
     * Time: 10:19
     * To change this template use File | Settings | File Templates.
     */

    module_load_include( 'constants.inc', 'scoga_core' );
    module_load_include( 'api.inc', 'scoga_core' );

    /**
     * Implements hook_services_resources().
     */

    function scoga_core_services_resources(){
        return array(
            'scoga_campaign'    => array(
                'index' => array(
                    'help'             => 'Retrieves all data linked to a specific campaign',
                    'file'             => array(
                        'type'   => 'services.inc',
                        'module' => 'scoga_core'
                    ),
                    'callback'         => 'scoga_service_campaign_index',
                    'access arguments' => array( SCOGA_PERM_REST_ACCESS_CAMPAIGN_DATA ),
                    'args'             => array(
                        array(
                            'name'        => 'uuid',
                            'type'        => 'string',
                            'description' => 'The UUID of the campaign node',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                    )
                ),
            ),
            'scoga_team'        => array(
                'index' => array(
                    'help'             => 'Retrieves all data of a team',
                    'file'             => array(
                        'file'   => 'services.inc',
                        'module' => 'scoga_core'
                    ),
                    'callback'         => 'scoga_service_team_index',
                    'access arguments' => array( SCOGA_PERM_REST_ACCESS_TEAM_DATA ),
                    'args'             => array(
                        array(
                            'name'        => 'uuid',
                            'description' => 'The UUID of the team node',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                        array(
                            'name'        => 'nid',
                            'description' => 'The nid of the team node',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                    )
                ),
            ),

            'scoga_player'      => array(
                'index' => array(
                    'help'             => 'Retrieves all data of a player',
                    'file'             => array(
                        'file'   => 'services.inc',
                        'module' => 'scoga_core'
                    ),
                    'callback'         => 'scoga_service_player_index',
                    'access arguments' => array( SCOGA_PERM_REST_ACCESS_PLAYER_DATA ),
                    'args'             => array(
                        array(
                            'name'        => 'uuid',
                            'description' => 'The UUID of the player',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                        array(
                            'name'        => 'uid',
                            'description' => 'The uid of the team node',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                    )
                ),
            ),

            'scoga_transaction' => array(
                'index' => array(
                    'help'             => 'Retrieves all transactions between two timestamps',
                    'file'             => array(
                        'file'   => 'services.inc',
                        'module' => 'scoga_core'
                    ),
                    'callback'         => 'scoga_service_transaction_index',
                    'access arguments' => array( SCOGA_PERM_REST_ACCESS_TRANSACTION_DATA ),
                    'args'             => array(
                        array(
                            'name'        => 'campaign_uuid',
                            'type'        => 'string',
                            'description' => 'The UUID of the campaign node',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                        array(
                            'name'        => 'begin_time',
                            'description' => 'The begintime (MS)',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                        array(
                            'name'        => 'end_time',
                            'description' => 'The end time (MS), default now',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                    )
                ),
            ),

        );
    }

    /**
     * implement hook_menu()
     */
    function scoga_core_menu(){
        $items = array();
        $items[ SCOGA_ADMIN_PAGE ] = array(
            'title'            => t( 'SCOGA settings' ),
            'description'      => t( 'General settings for SCOGA' ),
            'page callback' => 'system_admin_menu_block_page',
            'access arguments' => array( SCOGA_PERM_ADMINISTER_SETTINGS ),
            'file' => 'system.admin.inc',
            'file path' => drupal_get_path('module', 'system'),
            'type' => MENU_NORMAL_ITEM,
        );
        $items[ SCOGA_ADMIN_PAGE . '/core' ]=array(
            'title'             => t( 'SCOGA core settings' ),
            'type'             => MENU_NORMAL_ITEM,
            'file'             => 'scoga_core.admin.inc',
            'page callback'    => 'drupal_get_form',
            'page arguments'   => array( 'scoga_core_settings_form' ),
            'access arguments' => array( SCOGA_PERM_ADMINISTER_SETTINGS ),
        );
        return $items;
    }


    /**
     * implement hook_cron
     */
    function scoga_core_cron(){
        module_load_include( 'cron.inc', 'scoga_core' );
        scoga_cron_determine_current_campaign();
    }

    /**
     * implements hook_scoga_current_campaign_changed
     * @param $new_nid
     * @param $old_nid
     */
    function scoga_core_scoga_current_campaign_changed( $new_nid, $old_nid ){
        module_load_include( 'module', 'userpoints_reset' );
        userpoints_reset_do();
        watchdog( 'SCOGA', 'all user points reset due to campaign switch' );
        module_load_include( 'api.player.inc', 'scoga_core' );
        scoga_award_default_credits_to_all_players();
    }

    /**
     * implements hook_user_insert
     * @param $edit
     * @param $account
     * @param $category
     */
    function scoga_core_user_insert(&$edit, $account, $category){
        module_load_include( 'api.player.inc', 'scoga_core' );
        scoga_award_default_credits_to_player( $account->uid );
    }