<?php
/**
 * Created by JetBrains PhpStorm.
 * User: creynder
 * Date: 27/04/12
 * Time: 21:47
 * To change this template use File | Settings | File Templates.
 */


    define( 'SCOGA_PERM_ADMINISTER_SETTINGS', 'scoga administer settings' );

    define( 'SCOGA_TIME_FORMAT', 'H:i:s d/m/Y' );

    define( 'SCOGA_CAMPAIGN_NODETYPE', 'nodetype_campaign' );
    define( 'SCOGA_CAMPAIGNTEAM_NODETYPE', 'nodetype_campaign_team' );
    define( 'SCOGA_TEAM_NODETYPE', 'nodetype_team' );
    define( 'SCOGA_CHECKIN_NODETYPE', 'nodetype_checkin' );
    define( 'SCOGA_READER_NODETYPE', 'nodetype_rfid_reader' );
    define( 'SCOGA_POINTS_VOCAB', 'userpoints' );

    define( 'SCOGA_SETTING_CHECKIN_COOLDOWN', 'scoga_settings_checkin_cooldown' );
    define( 'SCOGA_SETTING_COMBOCHECKIN_TIMEFRAME', 'scoga_settings_combocheckin_timeframe' );
    define( 'SCOGA_SETTING_DEFAULT_USERNAME', 'scoga_settings_default_username' );
    define( 'SCOGA_SETTING_CURRENT_CAMPAIGN_NID', 'scoga_settings_current_campaign_nid' );
    define( 'SCOGA_SETTING_DETERMINECAMPAIGN_CRON_INTERVAL', 'scoga_settings_determine_campaign_cron_interval' );
    define( 'SCOGA_SETTING_DETERMINECAMPAIGN_NEXT_EXECUTION', 'scoga_settings_determine_campaign_next_execution' );
    define( 'SCOGA_SETTING_DEFAULT_CREDITS', 'scoga_settings_default_credits' );

    define( 'SCOGA_DEFAULT_TEAM', 26 );
    define( 'SCOGA_CHECKINPARTNER_RTID', 1 );
    define( 'SCOGA_ADMIN_PAGE', 'admin/config/scoga' );
    define( 'SCOGA_CREDITS_TID', '3' );
    define( 'SCOGA_PLAYER_ROLE', 4 );

    define( 'SCOGA_PERM_REST_ACCESS_CAMPAIGN_DATA', 'access content' );
    define( 'SCOGA_PERM_REST_ACCESS_TEAM_DATA', 'access content' );
    define( 'SCOGA_PERM_REST_ACCESS_PLAYER_DATA', 'access content' );
    define( 'SCOGA_PERM_REST_ACCESS_TRANSACTION_DATA', 'access content' );

