<?php
/**
 * Created by JetBrains PhpStorm.
 * User: creynder
 * Date: 13/12/11
 * Time: 12:36
 * To change this template use File | Settings | File Templates.
 */

const PERM_CREATE_CHECKIN = 'create checkin node';

/**
 * Implements hook_permission().
 */
function scoga_resources_permission() {
    return array(
         PERM_CREATE_CHECKIN => array(
            'title' => t('Create "Checkin" node'),
            'description' => t('Create a node of content type "Checkin" through the REST service.<br/>'),
        ),
    );
}

/**
* Implements hook_services_resources().
*/
function scoga_resources_services_resources(){
    return array(
        'reader_checkin' => array(
            'create' => array(
                'help' => 'Creates a node of content type "Checkin"',
                'file' => array(
                    'file' => 'inc',
                    'module' => 'scoga_resources'
                ),
                'callback' => 'create_checkin_node',
                'access arguments' => array( 'create checkin node' ),
                'args' => array(
                    array(
                        'name' => 'cardID',
                        'type' => 'string',
                        'description' => 'The unique ID of the card',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'readerID',
                        'type' => 'string',
                        'description' => 'The unique ID of the RFID reader',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'timestamp',
                        'type' => 'int',
                        'description' => 'The unix epoch timestamp of checkin',
                        'source' => 'data',
                        'optional' => TRUE,
                        'default value' => -1
                    ),
                )
            )
        ),
    );
}
