<?php
/**
 * Created by JetBrains PhpStorm.
 * User: creynder
 * Date: 13/12/11
 * Time: 12:36
 * To change this template use File | Settings | File Templates.
 */
module_load_include( 'inc', 'scoga', 'scoga.constants' );

define( 'SCOGA_PERM_REST_ACCESS_CREATE_CHECKIN', 'access create checkin' );
define( 'SCOGA_PERM_REST_EXECUTE_CREATE_CHECKIN', 'execute create checkin' );
define( 'SCOGA_PERM_REST_ACCESS_REGISTER_READER', 'access register rfid reader' );
define( 'SCOGA_PERM_REST_EXECUTE_REGISTER_READER', 'execute register rfid reader' );
define( 'SCOGA_PERM_REST_ACCESS_REGISTER_CARD', 'access register rfid card' );
define( 'SCOGA_PERM_REST_EXECUTE_REGISTER_CARD', 'execute register rfid card' );

/**
 * Implements hook_permission().
 */
function scoga_resources_permission() {
    return array(
        SCOGA_PERM_REST_ACCESS_CREATE_CHECKIN => array(
            'title' => t('Access "Checkin" creation service'),
            'description' => t('Access to the checkin creation service.<br/><strong>SHOULD BE ALLOWED FOR ANONYMOUS!</strong>'),
        ),
        SCOGA_PERM_REST_EXECUTE_CREATE_CHECKIN => array(
            'title' => t('Create "Checkin" node'),
            'description' => t('Create a node of content type "Checkin" through the REST service.<br/>'),
        ),
        SCOGA_PERM_REST_ACCESS_REGISTER_READER => array(
            'title' => t( 'Access register RFID reader service' ),
            'description' => t( 'Access to the RFID reader registration service<br/><strong>SHOULD BE ALLOWED FOR ANONYMOUS!</strong>' ),
        ),
        SCOGA_PERM_REST_EXECUTE_REGISTER_READER => array(
            'title' => t( 'Register RFID reader' ),
            'description' => t( 'Register an RFID reader to be used with SCOGA' ),
        ),
        SCOGA_PERM_REST_ACCESS_REGISTER_CARD => array(
            'title' => t( 'Access register RFID card service' ),
            'description' => t( 'Access to the RFID card registration service<br/><strong>FOR TESTING PURPOSES ONLY, DISABLE ON LIVE SITE</strong>' ),
        ),
        SCOGA_PERM_REST_EXECUTE_REGISTER_CARD => array(
            'title' => t( 'Register RFID card' ),
            'description' => t( 'Register an RFID card to be used with SCOGA' ),
        ),
    );
}

/**
* Implements hook_services_resources().
*/
function scoga_resources_services_resources(){
    return array(
        'reader_checkin' => array(
            'create' => array(
                'help' => 'Creates a node of content type "Checkin"',
                'file' => array(
                    'file' => 'inc',
                    'module' => 'scoga_resources'
                ),
                'callback' => 'reader_checkin',
                'access arguments' => array( SCOGA_PERM_REST_ACCESS_CREATE_CHECKIN ),
                'args' => array(
                    array(
                        'name' => 'cardID',
                        'type' => 'string',
                        'description' => 'The unique ID of the card',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'readerID',
                        'type' => 'string',
                        'description' => 'The unique ID of the RFID reader',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'timestamp',
                        'type' => 'int',
                        'description' => 'The unix epoch timestamp of checkin',
                        'source' => 'data',
                        'optional' => TRUE,
                        'default value' => -1
                    ),
                )
            )
        ),
        'register_reader' => array(
            'create' => array(
                'help' => 'Register an RFID reader to be used with SCOGA',
                'file' => array(
                    'file' => 'inc',
                    'module' => 'scoga_resources'
                ),
                'callback' => 'register_reader',
                'access arguments' => array( SCOGA_PERM_REST_ACCESS_REGISTER_READER ),
                'args' => array(
                    array(
                        'name' => 'cardID',
                        'type' => 'string',
                        'description' => 'The unique ID of the card',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'readerID',
                        'type' => 'string',
                        'description' => 'The unique ID of the RFID reader',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'timestamp',
                        'type' => 'int',
                        'description' => 'The unix epoch timestamp of checkin',
                        'source' => 'data',
                        'optional' => TRUE,
                        'default value' => -1
                    ),
                )
            )
        ),
        'register_card' => array(
            'create' => array(
                'help' => 'Register an RFID card to be used with SCOGA',
                'file' => array(
                    'file' => 'inc',
                    'module' => 'scoga_resources'
                ),
                'callback' => 'register_card',
                'access arguments' => array( SCOGA_PERM_REST_ACCESS_REGISTER_CARD ),
                'args' => array(
                    array(
                        'name' => 'cardID',
                        'type' => 'string',
                        'description' => 'The unique ID of the card',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'readerID',
                        'type' => 'string',
                        'description' => 'The unique ID of the RFID reader',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                )
            )
        ),

    );
}
