<?php
/**
 * Created by JetBrains PhpStorm.
 * User: creynder
 * Date: 13/12/11
 * Time: 12:36
 * To change this template use File | Settings | File Templates.
 */
/**
 * Implements hook_perm().
 */

function scoga_resources_permission() {
    return array(
        'retrieve checkin nodes list' => array(
            'title' => t('Retrieve "Checkin" nodes list'),
            'description' => t('Retrieve a list of "Checkin" nodes'),
        ),
        'create checkin node' => array(
            'title' => t('Create "Checkin" node'),
            'description' => t('Create a node of content type "Checkin" through the REST service.'),
        ),
    );
}

/**
* Implements hook_services_resources().
*/
function scoga_resources_services_resources(){
    return array(
        'reader_checkin' => array(
            'index' => array(
                'help' => 'List of "Checkin"',
                'file' => array(
                    'file' => 'inc',
                    'module' => 'scoga_resources'
                ),
                'callback' => 'retrieve_checkin_nodes_list',
                'access arguments' => array( 'retrieve checkin nodes list' ),
                'args' => array(
                    array(
                        'name' => 'cardID',
                        'type' => 'string',
                        'description' => 'The unique ID of the card',
                        'source' => 'param',
                        'optional' => TRUE,
                    ),
                ),
            ),
            'create' => array(
                'help' => 'Creates a node of content type "Checkin"',
                'file' => array(
                    'file' => 'inc',
                    'module' => 'scoga_resources'
                ),
                'callback' => 'create_checkin_node',
                'access arguments' => array( 'create checkin node' ),
                'args' => array(
                    array(
                        'name' => 'cardID',
                        'type' => 'string',
                        'description' => 'The unique ID of the card',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'readerID',
                        'type' => 'string',
                        'description' => 'The unique ID of the RFID reader',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'timestamp',
                        'type' => 'int',
                        'description' => 'The unix epoch timestamp of checkin',
                        'source' => 'data',
                        'optional' => TRUE,
                        'default value' => -1
                    ),
                )
            )
        ),
    );
}
