<?php
    /**
     * Created by JetBrains PhpStorm.
     * User: creynder
     * Date: 12/04/12
     * Time: 10:19
     * To change this template use File | Settings | File Templates.
     */

    define( 'SCOGA_PERM_REST_ACCESS_OVERVIEW_DATA', 'access content' );
    define( 'SCOGA_PERM_REST_ACCESS_MESSAGES_DATA', 'access content' );
    define( 'SCOGA_MESSAGES_NODETYPE', 'nodetype_logmessages' );

    /**
     * Implements hook_services_resources().
     */

    function scoga_aggregated_services_resources(){
        return array(
            'scoga_overview'    => array(
                'index' => array(
                    'help'             => 'Retrieves a snapshot of the SCOGA state',
                    'file'             => array(
                        'type'   => 'services.inc',
                        'module' => 'scoga_aggregated'
                    ),
                    'callback'         => 'scoga_service_overview_index',
                    'access arguments' => array( SCOGA_PERM_REST_ACCESS_OVERVIEW_DATA ),
                ),
            ),
            'scoga_message'    => array(
                'index' => array(
                    'help'             => 'Retrieves all messages',
                    'file'             => array(
                        'type'   => 'services.inc',
                        'module' => 'scoga_aggregated'
                    ),
                    'callback'         => 'scoga_service_message_index',
                    'access arguments' => array( SCOGA_PERM_REST_ACCESS_MESSAGES_DATA ),
                    'args'             => array(
                        array(
                            'name'        => 'last_nid',
                            'type'        => 'string',
                            'description' => 'Messages with a nid higher than last_nid will be retrieved',
                            'source'      => 'param',
                            'optional'    => TRUE
                        ),
                    )
                ),
            ),
        );
    }

